services:
  taxonomy-database:
    image: localcosmos/lc-taxonomy
    container_name: lc-taxonomy-database-live
    restart: always
    networks:
      - lc-taxonomy-network
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=linnaeus
      - POSTGRES_PASSWORD=tAx0n0my!
      - POSTGRES_DB=taxonomy
    volumes:
      - "taxonomy_data:/var/lib/postgresql/data"

volumes:
  taxonomy_data:

networks:
  lc-taxonomy-network:
    name: lc-taxonomy-network
    external: true
